[target.riscv64gc-unknown-linux-musl]
linker = "rust-lld"

[target.aarch64-unknown-linux-musl]
linker = "rust-lld"

[target.armv7-unknown-linux-musleabihf]
linker = "rust-lld"

[target.arm-unknown-linux-musleabihf]
linker = "rust-lld"

[target.i686-unknown-linux-musl]
linker = "rust-lld"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
rustflags = ["-C", "target-feature=+crt-static"]
